[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run migrate && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 